import type { Issue, Project, Session } from "@uxcue/schema";
import { renderIssueBlock, type RenderOptions } from "./issue-md";

export interface ReviewInput {
  project: Project;
  session: Session;
  issues: Issue[];
  version?: string;
}

const AGENT_INSTRUCTIONS =
  "Use the issue IDs in commits, PRs, and comments. Prefer existing design " +
  "tokens and component patterns. Verify each fix against the captured viewport " +
  "and current responsive behavior.";

function summaryRow(i: Issue): string {
  return `| ${i.displayId} | ${i.page.pathname} | ${i.type} | ${i.severity} | ${i.status} | ${i.assigneeHint} | ${i.title} |`;
}

/** Group issues by page pathname, preserving first-seen order. */
function groupByPage(issues: Issue[]): Map<string, Issue[]> {
  const groups = new Map<string, Issue[]>();
  for (const issue of issues) {
    const key = issue.page.pathname;
    (groups.get(key) ?? groups.set(key, []).get(key)!).push(issue);
  }
  return groups;
}

/**
 * Full session review.md (docs/04). Self-contained and agent-agnostic (D014):
 * an agent with zero UXCue knowledge should locate and fix issues from this
 * bundle alone.
 */
export function renderReviewMarkdown(
  { project, session, issues, version }: ReviewInput,
  opts: RenderOptions = {},
): string {
  const lines: string[] = [];
  lines.push(`# UI/UX Review: ${session.name}`, "");
  lines.push(`Generated by UXCue ${version ?? "0.0.1"}`);
  lines.push(`Date: ${new Date().toISOString().slice(0, 10)}`);
  lines.push(`Project: ${project.name}`);
  if (session.baseUrl ?? project.baseUrl) {
    lines.push(`Base URL: ${session.baseUrl ?? project.baseUrl}`);
  }
  lines.push(`Items: ${issues.length}`, "");

  lines.push("## Summary", "");
  lines.push("| ID | Page | Type | Severity | Status | Assignee | Title |");
  lines.push("| --- | --- | --- | --- | --- | --- | --- |");
  for (const i of issues) lines.push(summaryRow(i));
  lines.push("");

  lines.push("## Agent Instructions", "", AGENT_INSTRUCTIONS, "");

  for (const [pathname, group] of groupByPage(issues)) {
    lines.push(`## Page: ${pathname}`, "");
    for (const issue of group) lines.push(renderIssueBlock(issue, opts), "");
  }

  return (
    lines
      .join("\n")
      .replace(/\n{3,}/g, "\n\n")
      .trimEnd() + "\n"
  );
}
