import { describe, it, expect } from "vitest";
import { renderReviewMarkdown, renderIssueMarkdown } from "../src/index";
import { project, session, issue } from "./fixtures";

describe("renderReviewMarkdown", () => {
  const md = renderReviewMarkdown({
    project,
    session,
    version: "0.0.1",
    issues: [
      issue(),
      issue({
        id: "i2",
        displayId: "UX-002",
        title: "Mobile nav overlaps title",
        type: "responsive",
        severity: "minor",
        page: {
          url: "https://app.example.com/responsive",
          origin: "https://app.example.com",
          pathname: "/responsive",
          capturedAt: "2026-07-04T20:00:00.000Z",
        },
      }),
    ],
  });

  it("has the header, project, and item count", () => {
    expect(md).toContain("# UI/UX Review: Billing polish");
    expect(md).toContain("Generated by UXCue 0.0.1");
    expect(md).toContain("Project: KtKAI Console");
    expect(md).toContain("Items: 2");
  });

  it("has a summary table with a row per issue", () => {
    expect(md).toContain("| ID | Page | Type | Severity | Status | Assignee | Title |");
    expect(md).toContain(
      "| UX-001 | /settings/billing | visual-defect | major | open | code-agent | Billing button wraps awkwardly |",
    );
    expect(md).toContain("| UX-002 | /responsive | responsive | minor | open | code-agent |");
  });

  it("groups issues by page", () => {
    expect(md).toContain("## Page: /settings/billing");
    expect(md).toContain("## Page: /responsive");
  });

  it("is agent-agnostic — neutral instructions, no vendor names", () => {
    expect(md).toContain("## Agent Instructions");
    expect(md.toLowerCase()).not.toMatch(/\bclaude\b|\bcodex\b|\bcursor\b|\bcopilot\b/);
  });

  it("renders the target, styles, and screenshot references", () => {
    expect(md).toContain('- Selector: `[data-testid="upgrade-plan-button"]`');
    expect(md).toContain("- BBox: 182x40 at 928,344");
    expect(md).toContain("- Viewport: 1440x900 @2x, light");
    expect(md).toContain("| min-height | 40px |");
    expect(md).toContain("- Element: `screenshots/UX-001-element.png`");
  });
});

describe("renderIssueMarkdown", () => {
  it("renders a standalone issue with its heading and feedback", () => {
    const md = renderIssueMarkdown(issue());
    expect(md).toContain("### UX-001: Billing button wraps awkwardly");
    expect(md).toContain("#### Feedback");
    expect(md).toContain("Assignee hint: code-agent");
  });

  it("handles a page-level note (no target) without crashing", () => {
    const md = renderIssueMarkdown(issue({ target: undefined, screenshots: {} }));
    expect(md).toContain("Page-level note (no element selected)");
    expect(md).not.toContain("#### Relevant Styles");
  });
});
